---
title: "Mapping Congressional Districtis"
author: 
- name: Hannah Sun
  affiliation: Smith College
date: "`r format(Sys.Date(), '%B %e, %Y')`"
output:
  html_document:
    toc: yes
    toc_depth: 2
    toc_float: yes
    fig_width: 7
    fig_height: 6
    # fig_caption: yes
    theme: lumen
    df_print: paged
    code_folding: show

---


```{r setup, include=FALSE}
# knitr::opts_chunk$set(echo = TRUE)
require(tidyverse)
library(leaflet)
library(tidycensus)
library(viridis)
require(sf)
library(knitr)
library(moderndive)
require(ggplot2)
require(ggmap)
library(maps)
library(RColorBrewer)  # You need the RColorBrewer library for palettes

```


## 82nd Congress
### January 3, 1951 to July 7, 1952
```{r 82District, include=FALSE}
get_congress_map_82 <- function(cong=113) {
  tmp_file <- tempfile()
  tmp_dir  <- tempdir()
  zp <- sprintf("https://cdmaps.polisci.ucla.edu/shp/districts082.zip",cong)
  download.file(zp, tmp_file)
  unzip(zipfile = tmp_file, exdir = tmp_dir)
  fpath <- paste(tmp_dir, sprintf("districtShapes/districts082.shp",cong), sep = "/")
  st_read(fpath)
}
```
```{r 82District-comp, include=FALSE}
cd114_82 <- get_congress_map_82(114)
cd114_82$DISTRICT <- as.numeric(cd114_82$DISTRICT)

```
```{r 82DistrictMap, echo=FALSE, warning=FALSE}
# mapStates = map("state", fill = TRUE, plot = FALSE)
pal_census <- colorNumeric(palette = "YlOrRd",
                        domain =  cd114_82$DISTRICT)
leaflet() %>%
  setView(lat = 40.0583, lng = -74.4057, zoom = 10) %>% 
  addProviderTiles("CartoDB.Positron") %>%
  addPolygons(data = cd114_82,
              opacity = 1.0,
              smoothFactor = 0.5,
              highlightOptions = highlightOptions(color = "white", weight =2,bringToFront = TRUE),
              fillColor = ~pal_census(DISTRICT),
              stroke = TRUE,
              weight = 1,
              fillOpacity = 0.5,
              label = ~DISTRICT
  #             labelOptions = labelOptions(
  #                 interactive = FALSE,
  # clickable = FALSE,
  # noHide = TRUE,
  # permanent = TRUE,
  # # style = list("font-weight" = "normal", padding = "3px 8px"),
  # textOnly = TRUE
  # )
) %>% 
  addLegend(data = cd114_82, title = "Districts",
            pal = pal_census,
            values=~DISTRICT)
 
```

## 87th Congress
### January 3, 1961 to October 13, 1962
```{r 87District, include=FALSE}
get_congress_map_87 <- function(cong=113) {
  tmp_file <- tempfile()
  tmp_dir  <- tempdir()
  zp <- sprintf("https://cdmaps.polisci.ucla.edu/shp/districts087.zip",cong)
  download.file(zp, tmp_file)
  unzip(zipfile = tmp_file, exdir = tmp_dir)
  fpath <- paste(tmp_dir, sprintf("districtShapes/districts087.shp",cong), sep = "/")
  st_read(fpath)
}
```
```{r 87District-comp, include=FALSE}
cd114_87 <- get_congress_map_87(114)
cd114_87$DISTRICT <- as.numeric(cd114_87$DISTRICT)

```
```{r 87DistrictMap, echo=FALSE, warning=FALSE}
# mapStates = map("state", fill = TRUE, plot = FALSE)
pal_census <- colorNumeric(palette = "YlOrRd",
                        domain =  cd114_87$DISTRICT)
leaflet() %>%
  setView(lat = 40.0583, lng = -74.4057, zoom = 10) %>% 
  addProviderTiles("CartoDB.Positron") %>%
  addPolygons(data = cd114_87,
              opacity = 1.0,
              smoothFactor = 0.5,
              highlightOptions = highlightOptions(color = "white", weight =2,bringToFront = TRUE),
              fillColor = ~pal_census(DISTRICT),
              stroke = TRUE,
              weight = 1,
              fillOpacity = 0.5,
              label = ~DISTRICT
  #             labelOptions = labelOptions(
  #                 interactive = FALSE,
  # clickable = FALSE,
  # noHide = TRUE,
  # permanent = TRUE,
  # # style = list("font-weight" = "normal", padding = "3px 8px"),
  # textOnly = TRUE
  # )
) %>% 
  addLegend(data = cd114_87, title = "Districts",
            pal = pal_census,
            values=~DISTRICT)
```

## 92nd Congress
### January 21, 1971 to October 18, 1972
```{r 92District, include=FALSE}
get_congress_map_92 <- function(cong=113) {
  tmp_file <- tempfile()
  tmp_dir  <- tempdir()
  zp <- sprintf("https://cdmaps.polisci.ucla.edu/shp/districts092.zip",cong)
  download.file(zp, tmp_file)
  unzip(zipfile = tmp_file, exdir = tmp_dir)
  fpath <- paste(tmp_dir, sprintf("districtShapes/districts092.shp",cong), sep = "/")
  st_read(fpath)
}
```
```{r 92District-comp, include=FALSE}
cd114_92 <- get_congress_map_92(114)
cd114_92$DISTRICT <- as.numeric(cd114_92$DISTRICT)

```
```{r 92DistrictMap, echo=FALSE, warning=FALSE}
# mapStates = map("state", fill = TRUE, plot = FALSE)
pal_census <- colorNumeric(palette = "YlOrRd",
                        domain =  cd114_92$DISTRICT)
leaflet() %>%
  setView(lat = 40.0583, lng = -74.4057, zoom = 10) %>% 
  addProviderTiles("CartoDB.Positron") %>%
  addPolygons(data = cd114_92,
              opacity = 1.0,
              smoothFactor = 0.5,
              highlightOptions = highlightOptions(color = "white", weight =2,bringToFront = TRUE),
              fillColor = ~pal_census(DISTRICT),
              stroke = TRUE,
              weight = 1,
              fillOpacity = 0.5,
              label = ~DISTRICT
  #             labelOptions = labelOptions(
  #                 interactive = FALSE,
  # clickable = FALSE,
  # noHide = TRUE,
  # permanent = TRUE,
  # # style = list("font-weight" = "normal", padding = "3px 8px"),
  # textOnly = TRUE
  # )
) %>% 
  addLegend(data = cd114_92, title = "Districts",
            pal = pal_census,
            values=~DISTRICT)
 
```



## 97th Congress
### January 5, 1981 to December 23, 1982
```{r 97District, include=FALSE}
get_congress_map_97 <- function(cong=113) {
  tmp_file <- tempfile()
  tmp_dir  <- tempdir()
  zp <- sprintf("https://cdmaps.polisci.ucla.edu/shp/districts097.zip",cong)
  download.file(zp, tmp_file)
  unzip(zipfile = tmp_file, exdir = tmp_dir)
  fpath <- paste(tmp_dir, sprintf("districtShapes/districts097.shp",cong), sep = "/")
  st_read(fpath)
}
```
```{r 97District-comp, include=FALSE}
cd114_97 <- get_congress_map_97(114)
cd114_97$DISTRICT <- as.numeric(cd114_97$DISTRICT)

```
```{r 97DistrictMap, echo=FALSE, warning=FALSE}
# mapStates = map("state", fill = TRUE, plot = FALSE)
pal_census <- colorNumeric(palette = "YlOrRd",
                        domain =  cd114_97$DISTRICT)
leaflet() %>%
  setView(lat = 40.0583, lng = -74.4057, zoom = 10) %>% 
  addProviderTiles("CartoDB.Positron") %>%
  addPolygons(data = cd114_97,
              opacity = 1.0,
              smoothFactor = 0.5,
              highlightOptions = highlightOptions(color = "white", weight =2,bringToFront = TRUE),
              fillColor = ~pal_census(DISTRICT),
              stroke = TRUE,
              weight = 1,
              fillOpacity = 0.5,
              label = ~DISTRICT
  #             labelOptions = labelOptions(
  #                 interactive = FALSE,
  # clickable = FALSE,
  # noHide = TRUE,
  # permanent = TRUE,
  # # style = list("font-weight" = "normal", padding = "3px 8px"),
  # textOnly = TRUE
  # )
) %>% 
  addLegend(data = cd114_97, title = "Districts",
            pal = pal_census,
            values=~DISTRICT)
 
```


## 102nd Congress
### January 3, 1991 to October 9, 1992
```{r 102District, include=FALSE}
get_congress_map_102 <- function(cong=113) {
  tmp_file <- tempfile()
  tmp_dir  <- tempdir()
  zp <- sprintf("https://cdmaps.polisci.ucla.edu/shp/districts102.zip",cong)
  download.file(zp, tmp_file)
  unzip(zipfile = tmp_file, exdir = tmp_dir)
  fpath <- paste(tmp_dir, sprintf("districtShapes/districts102.shp",cong), sep = "/")
  st_read(fpath)
}
```
```{r 102District-comp, include=FALSE}
cd114_102 <- get_congress_map_102(114)
cd114_102$DISTRICT <- as.numeric(cd114_102$DISTRICT)

```
```{r 102DistrictMap, echo=FALSE, warning=FALSE}
# mapStates = map("state", fill = TRUE, plot = FALSE)
pal_census <- colorNumeric(palette = "YlOrRd",
                        domain =  cd114_102$DISTRICT)
leaflet() %>%
  setView(lat = 40.0583, lng = -74.4057, zoom = 10) %>% 
  addProviderTiles("CartoDB.Positron") %>%
  addPolygons(data = cd114_102,
              opacity = 1.0,
              smoothFactor = 0.5,
              highlightOptions = highlightOptions(color = "white", weight =2,bringToFront = TRUE),
              fillColor = ~pal_census(DISTRICT),
              stroke = TRUE,
              weight = 1,
              fillOpacity = 0.5,
              label = ~DISTRICT
  #             labelOptions = labelOptions(
  #                 interactive = FALSE,
  # clickable = FALSE,
  # noHide = TRUE,
  # permanent = TRUE,
  # # style = list("font-weight" = "normal", padding = "3px 8px"),
  # textOnly = TRUE
  # )
) %>% 
  addLegend(data = cd114_102, title = "Districts",
            pal = pal_census,
            values=~DISTRICT)
```


## 107th Congress
### January 3, 2001 to November 22, 2002
```{r 107District, include=FALSE}
get_congress_map_107 <- function(cong=113) {
  tmp_file <- tempfile()
  tmp_dir  <- tempdir()
  zp <- sprintf("https://cdmaps.polisci.ucla.edu/shp/districts107.zip",cong)
  download.file(zp, tmp_file)
  unzip(zipfile = tmp_file, exdir = tmp_dir)
  fpath <- paste(tmp_dir, sprintf("districtShapes/districts107.shp",cong), sep = "/")
  st_read(fpath)
}
```
```{r 107District-comp, include=FALSE}
cd114_107 <- get_congress_map_107(114)
cd114_107$DISTRICT <- as.numeric(cd114_107$DISTRICT)

```
```{r 107DistrictMap, echo=FALSE, warning=FALSE}
# mapStates = map("state", fill = TRUE, plot = FALSE)
pal_census <- colorNumeric(palette = "YlOrRd",
                        domain =  cd114_107$DISTRICT)
leaflet() %>%
  setView(lat = 40.0583, lng = -74.4057, zoom = 10) %>% 
  addProviderTiles("CartoDB.Positron") %>%
  addPolygons(data = cd114_107,
              opacity = 1.0,
              smoothFactor = 0.5,
              highlightOptions = highlightOptions(color = "white", weight =2,bringToFront = TRUE),
              fillColor = ~pal_census(DISTRICT),
              stroke = TRUE,
              weight = 1,
              fillOpacity = 0.5,
              label = ~DISTRICT
  #             labelOptions = labelOptions(
  #                 interactive = FALSE,
  # clickable = FALSE,
  # noHide = TRUE,
  # permanent = TRUE,
  # # style = list("font-weight" = "normal", padding = "3px 8px"),
  # textOnly = TRUE
  # )
) %>% 
  addLegend(data = cd114_107, title = "Districts",
            pal = pal_census,
            values=~DISTRICT)
```

## 112th Congress
### January 5, 2011 to January 3, 2013
```{r 112District, include=FALSE}
get_congress_map_112 <- function(cong=113) {
  tmp_file <- tempfile()
  tmp_dir  <- tempdir()
  zp <- sprintf("https://cdmaps.polisci.ucla.edu/shp/districts112.zip",cong)
  download.file(zp, tmp_file)
  unzip(zipfile = tmp_file, exdir = tmp_dir)
  fpath <- paste(tmp_dir, sprintf("districtShapes/districts112.shp",cong), sep = "/")
  st_read(fpath)
}
```
```{r 112District-comp, include=FALSE}
cd114_112 <- get_congress_map_112(114)
cd114_112$DISTRICT <- as.numeric(cd114_112$DISTRICT)

```
```{r 112DistrictMap, echo=FALSE, warning=FALSE}
# mapStates = map("state", fill = TRUE, plot = FALSE)
pal_census <- colorNumeric(palette = "YlOrRd",
                        domain =  cd114_112$DISTRICT)
leaflet() %>%
  setView(lat = 40.0583, lng = -74.4057, zoom = 10) %>% 
  addProviderTiles("CartoDB.Positron") %>%
  addPolygons(data = cd114_112,
              opacity = 1.0,
              smoothFactor = 0.5,
              highlightOptions = highlightOptions(color = "white", weight =2,bringToFront = TRUE),
              fillColor = ~pal_census(DISTRICT),
              stroke = TRUE,
              weight = 1,
              fillOpacity = 0.5,
              label = ~DISTRICT
  #             labelOptions = labelOptions(
  #                 interactive = FALSE,
  # clickable = FALSE,
  # noHide = TRUE,
  # permanent = TRUE,
  # # style = list("font-weight" = "normal", padding = "3px 8px"),
  # textOnly = TRUE
  # )
) %>% 
  addLegend(data = cd114_112, title = "Districts",
            pal = pal_census,
            values=~DISTRICT)
```

